title: Experience
jobs:
  - period: 09/2025 - Now
    title: Full Stack Developer
    company: Freelancer
    url: https://lumarik.com
    description: >-
      Developed a dashboard application for centralized management and analysis
      of marketplace data through Mirakl API integration. Designed and
      implemented a scalable backend using Supabase, including database schema
      and data pipelines for marketplace analytics. Built serverless data
      processing workflows with Supabase Edge Functions (Deno) to ingest and
      transform large CSV datasets into structured database records. Integrated
      the Mirakl API to automate sales data ingestion, implementing incremental
      synchronization and data consistency mechanisms. The frontend of the
      application was tested using Playwright and Vitest, while the backend was
      tested using Deno tests along with pgTAP.
    tags:
      - Next.js
      - React
      - TypeScript
      - Supabase
      - Playwright
      - Vitest
      - TailwindCSS
      - SQL
  - period: 09/2024 - 04/2025
    title: Junior Frontend Developer
    company: Fluo IT Marcin Witecki
    url: '#'
    description: >-
      I worked on a copyright management system for the company Kopipol. I
      participated in designing and developing user interfaces (UX/UI) and
      tested the created screens for functionality and usability. The project
      was developed following the Agile methodology with Scrum, built with
      React, TailwindCSS, and ShadCN, and integrated with a REST API. Version
      control and collaboration were managed using Git.
    tags:
      - React
      - TypeScript
      - Tailwind CSS
      - REST APIs
      - TanStac table & query
  - period: 07/2022 - 08/2022
    title: Intern
    company: OptiBuy SP. z o.o.
    url: '#'
    description: >-
      I developed web APIs using FastAPI and prepared data for training a model
      used to verify company websites. I worked in a Scrum team following Agile
      methodology.
    tags:
      - Python
      - FastAPI
      - Git
      - REST APIs
      - Python unittest Framework
